### ISSUE TITLE
Layout problems on mobile

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/knora.org#6]
The logo is truncated, and the text "Knowledge Organization..." seems too big:

![2018-07-04 09 16 51](https://user-images.githubusercontent.com/558389/42262388-721400c2-7f6b-11e8-9e09-8adc5dec8151.png)

**Comment by kilchenmann** [comment]
Oh yes... I didn't tested the responsive design on everything. Damn. I will fix it...
